In [67]:
#Importing the libraries

#For all mathematical tools
import numpy as np   

#For data plotting
import matplotlib.pyplot as plt

#For importing and managing datasets
import pandas as pd  

In [68]:
#Importing dataset
dataset = pd.read_csv('Data.csv')

#iloc['rows','columns'] => Select all rows, and all the columns except the last one
X = dataset.iloc[:,:-1].values

#Selecting all rows of column '3'
y = dataset.iloc[:,3].values 

In [69]:
#Taking care of missing data
from sklearn.impute import SimpleImputer


missingvalues = SimpleImputer(missing_values = np.nan, strategy='mean')

#Fit all rows of only the column 1 and 2 (the upperbound is excluded, hence 3 won't be counted, lowerbound is included)
missingvalues = missingvalues.fit(X[:,1:3])

#Using the transform method of imputer object, we transform the columns needed as per the configuration
X[:,1:3] = missingvalues.transform(X[:,1:3])
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [70]:
#Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

#Encoding the countries (column 0) of the dataset for independent variables
columnTransformer_x = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(columnTransformer_x.fit_transform(X), dtype = np.str)

#Encoding the purchase variable (dependent variable)
#We only need LabelEncoder 
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [76]:
#Splitting data into training and test set
from sklearn.model_selection import train_test_split 
X_train , X_test, y_train, y_test = train_test_split(X , y, test_size = 0.2 , random_state = 0)


array([0, 0])

In [79]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])